//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BookingID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailID { get; set; }
        public string StylistName { get; set; }
        public string StylistService { get; set; }
        public System.DateTime DateForBooking { get; set; }
        public System.TimeSpan TimeForBooking { get; set; }
    
        public virtual User User { get; set; }
    }
}
